spring:
  application:
    name: letta-health-agents
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8085
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

letta:
  api:
    base-url: ${LETTA_API_URL:http://localhost:8283}
    api-key: ${LETTA_API_KEY:}
    timeout: 60s
    default-model: "letta/letta-free"
    default-embedding: "letta/letta-free"
    max-retries: 3
    retry-delay: 1s

logging:
  level:
    com.health.agents: DEBUG
    retrofit2: DEBUG
    okhttp3: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 